index.html

Suppression de virgules inutiles

---

_sass/_specifics.scss
appel-a-sujets.html
index.html

Feature : formulaire 2018
- Changement du formulaire vers le nouveau : https://docs.google.com/forms/d/1PcsYY8K9eQcUOg1jO1S60YE5CcVNbinfJu6zhAAj5W4/edit
- Ajout d'un champ "Durée de ta présentation"
- Suppression du champs "Si le public ne devrait retenir..."
- Modification de la description 2017 => 2018
@sudweb/thym

Formulaire 2018

---

_includes/navigation.html
index.html

Début de contribution des contenus fournis par @Julia-barbelane.
Page d'accueil, navigation.
@sudweb/thym

Début de modification des contenus

---

appel-a-sujets.html

Formulaire pas nécessairement inclusif, et des choses importantes dans les placeholder.
- Modification des libelés et des placeholders
@sudweb/thym

Proposition reformulation formulaire

---

_sass/_componants.scss
_sass/_layout.scss
index.html

- Ajout des sections pour expliquer ce que sont les confs et le forum ouvert
- J'ai enlevé l'animation sur le header aussi pour ne laisser que le fond orange (trop de rouge c'est agressif)
Preview : https://lellex-sudweb.netlify.com/
@sudweb/thym

Ajout des section conférences et forum ouvert

---

appel-a-sujets.html

Remove form heroes header and change end date

---

index.html

Aligné au centre, le texte explication est difficile à lire.
Alignement à gauche.
@sudweb/thym

Meilleure lisibilité

---

_sass/_team.scss

Les avatars de la Thym sont tristes !
Les avatars de la Thym sont colorés ;)
@sudweb/thym

De la couleur pour nos avatars

---

404.html
appel-a-sujets.html

- @Julia-barbelane avait fait des retours sur le Slack qui n'avaient pas été intégrés
- On ne mentionnait pas les formats traditionnels de conférence
- On avait toujours les héros sur la 404
- Wording sur la page d'appel à sujets
- Retrait des héros de la 404
@bertrandkeller : j'ai essayé des fonds colorés pour occuper l'espace quand les images des bannières ne sont pas chargées. Le résultat n'est pas très heureux donc j'ai laissé tel quel.
@sudweb/thym

Corrections diverses

---

_includes/navigation.html
_sass/_layout.scss
index.html

Aspect d'un bouton CTA dans une section. 
- Changement du type de bouton en modifiant la classe dans le html
@sudweb/thym

Style boutonctacolor

---

_includes/navigation.html
_sass/_layout.scss

Transition du orange au rouge sur le logo
- Suppression de l'animation en css sur le svg
@sudweb/thym

Suppression de la transition sur le logo

---

_config.yml
_data/navigation.yml
_data/translations.yml
_includes/navigation.html
en/index.html
index.html

- Dans la navigation, la page active n'était pas marquée
- La page active est marquée
@sudweb/thym

Navigation: marquage du lien actif

---

en/index.html

Reprise de la dernière modif de @lellex sur le form EN
(par contre chez moi ça ne rentre toujours pas dans la hauteur. Si on voulait améliorer, il faudrait calculer des tailles avec des `vh` ou du script. Proposition : attendre et voir ce que la refonte de @Twikito change, d'abord.)

Modifications de @lellex appliquées à la version EN

---

_includes/serviceworkers.html
_layouts/default.html
manifest.json
offline.md
sw.js

Faire du site une PWA
- Ajout d'un fichier sw.js
- Ajout d'un include pour le code d'appel de sw.js
- Ajout d'un page offline (pareil que la 404)
@sudweb/thym

Pwa lighthouseimprovment

---

appel-a-sujets.html
en/cfp.html

Suppression de la notion de super-héros dans les placeholders de l'appel à orateurs
- Clark Kent devient Amélie Poulain
- on ne parle plus de gentil ou de méchant mais de bonheur
@sudweb/thym

changement des placeholders du CFP

---

index.html

explications de pourquoi on fait de l'immersif cette année + lien vers article
- voir au dessus
-
-
@sudweb/thym

modif section hébergement

---

index.html

elle précise le fonctionnement de la répartition des chambres
- au dessus
-
-
@sudweb/thym

maj contenu section hébergement

---

index.html

Maj du titre sur le conseil de Sabine Safi que j'ai trouvé pertinent
- remplacement du "plutôt" en "surtout"
-
-
@sudweb/thym

remplacement du "plutôt" en "surtout"

---

_config.yml
_data/translations.yml
_includes/footer.html
_includes/head.html
_layouts/default.html
_sass/_base.scss
code-of-conduct.md

Ajout du CoC fr

---

_includes/footer.html
code-of-conduct.md
en/code-of-conduct.md
en/thym.md

- Le Code of Conduct n'était pas disponible en anglais.
- Le Code of Conduct est disponible dans un très mauvais anglais
Lire : https://5a57d99e4c4b931096d37f84--ranger-combat-60823.netlify.com/en/code-of-conduct/
@sudweb/thym

Code of Conduct, a translation attempt

---

code-of-conduct.md

Deux petites erreurs de conjugaison
- pas de "s" à l'impératif singulier pour les verbes du premier groupe
- accord avec le sujet dans la seconde phrase corrigée
-
@sudweb/thym

Corrections de conjugaison

---

code-of-conduct.md

Place le contexte en amont ce qui adoucit le CoC
@sudweb/thym

remonte le pourquoi

---

code-of-conduct.md

adoucir intro + appuyer le contexte
- ajout d'un sous-titre au titre 
- ajout de texte dans l'intro (inspiré par la posture d'O'Reilly"
-
@sudweb/thym

modif intro pour qu'elle soit plus douce

---

code-of-conduct.md

elle adoucit l'injonction des comportement qu'on veut pas trop voir
- reformulation des titres
- précision dragues/avance
- ajout d'une question pour architecturer le propos
@sudweb/thym

Maj texte sur cptmt qu'on veut et qu'on veut pas

---

code-of-conduct.md

Le champ lexical et l'usage de la deuxième personne peuvent donner l'impression que nous ne nous adressons pas à des adultes.
Proposition d'un ton plus formel mais tout aussi clair sur ses intentions.
@sudweb/thym, notamment @Julia-barbelane

Proposition de modification du ton employé

---

en/cfp.html

In English we don't really say "animation" when describing talks. Switched some content to more popular colloquialisms.
Fixes #
-
-
-
@sudweb/thym

some suggested changes

---

en/accomodation-alternatives.html

a few grammatical edits

---

en/code-of-conduct.md

This needs help. This is not an empowering code of conduct and can lead to further issues. I'll comment on that part later thru an "issue". I did not finish editing.
Fixes #
-
-
-
@sudweb/thym

Made a few grammatical improvements

---

code-of-conduct.md

Mot inconfortable aurait tendance à délégitimer la situation.
- remplacement/suppression du mot
-
-
@sudweb/thym

remplacement du mot "inconfortable"

---

code-of-conduct.md

Enlève une phrase un peu "trop marketing" à mon goût ^^
- retrait "SudWeb apparait....accueillant" dans l'intro
-
-
@sudweb/thym

retrait "SudWeb apparait....accueillant" trop market ?

---

code-of-conduct.md

ajout contact Julia
- ajout contacte Julia
-
-
@sudweb/thym

ajout contact Julia

---

code-of-conduct.md

"la suite dépend de vous" pouvait réduire un peu l'idée qu'on va l'aider
- enlève "la suite dépend de vous" question "que faire si je subi  une situation oppressive"
-
-
@sudweb/thym

enlève "la suite dépend de vous"

---

_config.yml
_includes/head.html
humans.txt

Suppression des vars SEO inutiles dans config.yml

---

_includes/navigation.html
_sass/layout/_navigation.scss
assets/js/main.js

Fixes #55 
- Un lien rôle bouton au lieu d'un bouton, cause bug navigateur sous Firefox
-
-
@sudweb/thym

Navigation ff

---

_includes/register-section.html
pages/fr/billeterie.html
pages/fr/financer.html

- Pas nécessairement de page qui explique clairement comment on peut financer Sud Web
- Proposition d'une page dédiée à ces explications
@sudweb/thym

Faq cagnotte

---

pages/fr/financer.html

Fixes orthographe
Qq corrections d'orthographes
@sudweb/thym

Correction d'orthographe/toussa

---

pages/en/contact.html
pages/fr/contact.html

Les labels n'étaient pas correctement liés aux champs.
Fix form accessibilité
- ajout d'`id`s
- modifs attributs `for` des `label`
@sudweb/thym

Fix accessibilité

---

_includes/header-page.html

En latin, Jehova commence par un I.
(oui, bon, Bambouseraie a un "e", ça sonnait moins percutant)
@sudweb/thym

Correction orthographe

---

pages/fr/index.html

Oubli d'écriture d'inclusive
-
-
-
@sudweb/thym

Fix écriture inclusive

---

pages/fr/coc.md

- Chacun et chacune n'ont pas de pluriel cf: http://activitesfle.over-blog.com/article-29248302.html 
- qq chevrons manquants
- qq apostrophes
- etc.
bises,
Nico
Orthographe, grammaire, toussa
@sudweb/thym

Bricoles diverses et (a)variées

---

_data/translations.yml
_includes/footer.html

J'imagine que c'était un artéfact du thème super-héros.
@sudweb/thym

Enlever "Who you gonna call?"

---

_data/sitemap.yml
_data/translations.yml
_includes/header-home.html
pages/fr/billeterie.html
pages/fr/index.html
pages/fr/venir-anduze.html

Pas de navigation jusqu'à la page
- Ajout de la page dans le menu
- Ajout d'un paragraphe de réassurance dans la billetterie
@newick @methylbro

Navigation jusqu'à la page

---

_data/writeups.yml

Ajout de mon témoignage perso => https://www.nicolas-hoffmann.net/source/1694-Retour-sur-Sud-Web-2016-a-Bordeaux.html
@sudweb/thym

Ajout témoignage 2016

---

_data/writeups.yml

UnE quête de sens ;)
@sudweb/thym

Correction typo

---

pages/fr/venir-anduze.html

Change l'ordre d'affichage, Détail pour le temps du bus
- Change l'ordre d'affichage
- Détail pour le temps du bus
@sudweb/thym

changed order, added bus details

---

pages/fr/financer.html

Oui, je suis un peu typo-nazi, mais bon, j’assume (chevrons, apostrophe).
@sudweb/thym

Typo updates

---

pages/fr/venir-anduze.html

De la typo-finasserie :)
@sudweb/thym

Encore des typo-détails ;)

---

pages/fr/venir-anduze.html

Coquille dans OpenStreetMap
Un caractère en plus (petit mais costo)
@sudweb/thym

Typo OpenStreetMap

---

_talks/conferences/de-linux-mandrake-a-eelo-des-projets-pour-les-citoyens-et-la-liberte.md

Orthographe (commme/comme)

---

_talks/conferences/tricot-et-programmation.md

Ajout d'un "p" (rapelle/rappelle)

---

_data/speakers.yml

Typo fix + changement d'URL pour Alexis Métaireau.

---

_data/speakers.yml
_includes/conferences.html
_talks/conferences/apprendre-a-apprendre-transmettre-en-perme-habilite-itineraire-nomade-et-fantome.md
_talks/conferences/casser-les-prejuges-grace-a-des-contenus-videos-inspirants.md
_talks/conferences/comment-un-passionne-de-logiciels-libres-choisit-de-devenir-brasseur.md
_talks/conferences/communaute-de-developpeurs-euses-en-petite-agglomeration-ce-n-est-pas-incompatible.md
_talks/conferences/de-la-salle-de-marches-a-youtube.md
_talks/conferences/de-linux-mandrake-a-eelo-des-projets-pour-les-citoyens-et-la-liberte.md
_talks/conferences/des-commandes-de-bieres-a-la-commande-en-ligne.md
_talks/conferences/je-suis-mon-propre-outil-de-travail.md
_talks/conferences/le-joyeux-melanges-des-cultures-professionnelles-soliste-de-haut-niveau-cheffe-dorchestre-ou-femme-orchestre.md
_talks/conferences/militer-pour-une-press-libre.md
_talks/conferences/prologue-dynamique.md
_talks/conferences/quinze-ans-de-metier-et-tant-besoin-de-mentors.md
_talks/conferences/s-accepter-sans-renoncer-3-lecons-tirees-de-mon-handicap-et-influant-ma-pratique-du-web.md
_talks/conferences/tricot-et-programmation.md
pages/en/programme.html
pages/fr/programme.html

- Pas de gestion des traductions du programme.
- Rapide gestion des traductions du programme.
@sudweb/thym

EN line-up

---

_data/speakers.yml

Petite correction orthographique

---

pages/fr/billetterie.html

Ajout section pour bénéficier du tarif réduit

---

_data/sitemap.yml
_data/translations.yml
_sass/base/_init.scss
_sass/base/_typo.scss
pages/en/infos-pratiques.html
pages/fr/infos-pratiques.html

Infos pratiques

---

_talks/conferences/comment-un-passionne-de-logiciels-libres-choisit-de-devenir-brasseur.md

- espaces avant ":"
- quelques apostrophes
@sudweb/thym
Bises !

Typodétails

---

_config.yml
_data/translations.yml
_includes/header-home.html
pages/en/billetterie.html
pages/fr/billetterie.html

Rouvrir la billetterie oblige les gens à être en permanence sur le site. Mieux vaudrait une liste d'attente.
Remplacement de la billeterie par la liste d'attente.
Visible sur http://borisschapira-sudweb.netlify.com/
@sudweb/thym

Liste d'attente tarif plein

---

pages/fr/infos-pratiques.html

Qq petites typos corrigées.
@sudweb/thym

Various typo fixes in infos-pratiques page

---

.travis.yml

Fix unfortunate line return
